### ISSUE TITLE
Cant connect to remote machine Ipad or Iphone

### ISSUE THREAD

**Issue by Grgur00** [LiamRiddell/Stremio-Server-Raspberry-PI#2]
My stremio works on my RPI but I can't connect my Iphone to same IP am I missing anything

**Comment by LiamRiddell** [comment]
Hi,

1. Are the devices on the same network?
2. Are the devices on the same subnet?
3. Make sure you are accessing the correct port

Without more information it’s hard to help.

**Comment by Grgur00** [comment]
Yes sorry I was writing this late at night forgot to include all the information. Devices are on same network I managed to troubleshoot it seems nginx is not startring I it doesnt see folder with SSL certificate. Thank you for your help. You can close this now
