### ISSUE TITLE
Torrenting on Ipad devices not working

### ISSUE THREAD

**Issue by Grgur00** [LiamRiddell/Stremio-Server-Raspberry-PI#3]
Whenever I try to watch video on ipad device I can't seem to enter it.
![WhatsApp Image 2024-12-22 at 14 36 02_227592f8](https://github.com/user-attachments/assets/4a5cb2bf-97c1-4404-9b7b-563a99477784)

All devices are on same network.

**Comment by Grgur00** [comment]
Just checked neither does playback work on RPI

**Comment by LiamRiddell** [comment]
1. You’d need to look at the configurations. 2. Make sure you’re using the specific version of stremio-server in the docker-compose as later versions broke. 
3. Check the ports are correct between nginx and stremio container. 
4. Validate https certificates
5. Focus on getting it working RP5 and then other devices 

It’s been a while so I’m unable to provide much support. Sorry.

**Comment by Grgur00** [comment]
It seems there is an issue with how stremio is routing their traffic in web version. To fix it once you enter https://XXX.XXX.XXX.XXX (X <- your IP) you will be redirected to https://app.strem.io/shell-v4.4/?streamingServer=https%3A%2F%2FXXX.XXX.XXX.XXX#/ you need to add your port in URL in our case that is 12470 so your URL will look something like this https://app.strem.io/shell-v4.4/?streamingServer=https%3A%2F%2XXX.XXX.XXX.XXX:12470#/ . This fixed the issue, and works flawlessly.

**Comment by LiamRiddell** [comment]
I remember that issue, sorry, I forgot about that. I’ll make a note and update the readme. Enjoy your setup!
